- build/kits/jboss-as7/docs/teiid/datasources/phoenix/create-phoenix-driver.cli
- build/kits/jboss-as7/docs/teiid/datasources/phoenix/create-phoenix-ds.cli
- build/kits/jboss-as7/docs/teiid/datasources/phoenix/modules/org/apache/phoenix/main/module.xml
- build/kits/jboss-as7/docs/teiid/datasources/phoenix/phoenix-ds.xml
- build/kits/jboss-as7/docs/teiid/datasources/phoenix/phoenix.xml
- build/kits/jboss-as7/docs/teiid/datasources/phoenix/readme.txt
phoenix driver depend on jre library class(com.sun.security.auth.module.UnixLoginModule), so if we add module, sun.jdk module should be added as dependency, also log4j can avoid Error class not found log.
> TEIID-2816: update phoenix ds create cli script

- connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/postgresql/PostgreSQLExecutionFactory.java
...tGisVersion when using postgresql jdbc translator
when I use postgresql translator of Teiid 8.10.0, it throw when deploying on jboss-as-7.4
the @TranslatorProperty annoation position is not right accoring to code in org.teiid.deployers.TranslatorUtil
getSetter method code
if (method.getName().startsWith("get")) { //$NON-NLS-1$
setter = "set"+setter.substring(3);//$NON-NLS-1$
}
else if (method.getName().startsWith("is")) { //$NON-NLS-1$
setter = "set"+setter.substring(2); //$NON-NLS-1$
}
else {
setter = "set"+method.getName().substring(0,1).toUpperCase()+method.getName().substring(1); //$NON-NLS-1$
}
this annoation can only be annoated on getXXX(), or isXXX() method.
> TEIID-3409 PostgreSQLExecutionFactory TranslatorProperty annotation in wrong place

- connectors/connector-infinispan-dsl/src/main/rar/META-INF/ra.xml
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/resource/adapter/infinispan/dsl/base/AbstractInfinispanManagedConnectionFactory.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/resource/adapter/infinispan/dsl/base/InfinispanConnectionImpl.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/ClassRegistry.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/DSLSearch.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/InfinispanConnection.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/InfinispanExecutionFactory.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/InfinispanUpdateExecution.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/metadata/ProtobufMetadataProcessor.java
- connectors/translator-infinispan-dsl/src/main/resources/org/teiid/translator/infinispan/dsl/i18n.properties
- connectors/translator-infinispan-dsl/src/test/java/org/jboss/as/quickstarts/datagrid/hotrod/query/domain/PersonCacheSource.java
- connectors/translator-infinispan-dsl/src/test/java/org/jboss/teiid/jdg_remote/pojo/AllTypes.java
- connectors/translator-infinispan-dsl/src/test/java/org/jboss/teiid/jdg_remote/pojo/AllTypesCacheSource.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/TestAbstractInfinispanConnectionFactory.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/TestInfinispanExecution.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/TestInfinispanExecutionFactory.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/TestInfinispanUpdateExecution.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/TestInfinispanUpdateUsingAllTypes.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/metadata/TestProtobufMetadataProcessor.java
- connectors/translator-infinispan-dsl/src/test/java/org/teiid/translator/infinispan/dsl/util/PersonSchemaVDBUtility.java
- connectors/translator-infinispan-dsl/src/test/resources/allTypes.proto
TEIID-3533 changed to use DataType.transform to convert values to the native object types for inserts and updates, TEIID-3535 add an NPE check for if a table has a primary key defined, fixed order by issue that wasnt using getNameInSource method logic.
> TEIID-3533 and TEIID-3535

- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/InfinispanExecutionFactory.java
TEIID-3627 changed to make supportsCompareCriteriaOrdered configurable by using a translator override
> TEIID-3627 changed to make supportsCompareCriteriaOrdered configurable

- pom.xml
Changed for product build only, so the javadocs can be produced at the same time as the -Prelease is done, in one step.
> Changed for product build only to produce javadocs

- build/pom.xml
- jboss-integration/src/test/java/org/teiid/jboss/TestJBossSecurityHelper.java
- pom.xml
Upgraded to use latest jboss-as and align picketbox, which requires fix to securityhelper
> Upgraded to use latest jboss-as and align picketbox, which requires fix to securityhelper

- connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/oracle/OracleExecutionFactory.java
- connectors/translator-jdbc/src/test/java/org/teiid/translator/jdbc/oracle/TestOracleTranslator.java
This might not be sufficient fix, due to possible issues with some specific Oracle 11g versions.
> TEIID-4134 Fix recursive CTE pushdown with Oracle

- connectors/translator-infinispan-cache/src/main/java/org/teiid/translator/infinispan/cache/InfinispanCacheExecutionFactory.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/InfinispanExecutionFactory.java
TEIID-4166 setting defaults for MaxDependentInPredicates and MaxInCriteriaSize for accessing JDG caches
> TEIID-4166 setting defaults

- jboss-integration/src/main/java/org/teiid/jboss/TeiidOperationHandler.java
The class of ### version has been changed from Integer to String.
> TEIID-4310: Sessions can not be shown in web-console runtime sub-panel

- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/db2/create-db2-xa-ds.cli
- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/mysql/create-mysql-xa-ds.cli
- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/oracle/create-oracle-xa-ds.cli
- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/postgresql/create-postgresql-xa-ds.cli
- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/sqlserver/jtds/create-jtds-xa-ds.cli
- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/sqlserver/native/create-ms-native-xa-ds.cli
- connectors/translator-jdbc/kits/wildfly/docs/teiid/datasources/teiid/create-teiid-xa-ds.cli
Without batch, "WFLYJCA0069: At least one xa-datasource-property is required for an xa-datasource" will throw.
> TEIID-4306: change to batch create xa ds

- connectors/translator-swagger/src/main/java/org/teiid/translator/swagger/JsonSerializer.java
- connectors/translator-swagger/src/main/java/org/teiid/translator/swagger/SwaggerMetadataProcessor.java
- connectors/translator-swagger/src/main/java/org/teiid/translator/swagger/SwaggerPlugin.java
- connectors/translator-swagger/src/main/resources/org/teiid/translator/swagger/i18n.properties
1. EmptyStackException in JsonSerializer.deserialize for unnamed arrays: check got empty stack
2. DDL generation: use swagger 'required' field to determine parameter NullType
3. Enhancement: Allow a user to specify a Swagger file as the source of metadata generation
> JIRA: TEIID-4326

- connectors/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/AbstractInfinispanManagedConnectionFactory.java
- connectors/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/InfinispanConnectionImpl.java
- connectors/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/InfinispanHotRodConnection.java
- connectors/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/InfinispanHotRodExecutionFactory.java
- connectors/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/metadata/ProtobufMetadataProcessor.java
- connectors/translator-infinispan-hotrod/src/test/java/org/teiid/translator/infinispan/hotrod/TestInfinispanHotRodConnection.java
- connectors/translator-infinispan-hotrod/src/test/resources/allTypesMetadata.ddl
- connectors/translator-infinispan-hotrod/src/test/resources/personMetadata.ddl
- connectors/translator-infinispan-hotrod/src/test/resources/personMetadataNoObject.ddl
- connectors/translator-object/src/main/java/org/teiid/translator/object/ObjectExecutionFactory.java
- connectors/translator-object/src/test/java/org/teiid/translator/object/metadata/TestAnnotationMetadataProcessor.java
TEIID-4409 the option to determine if configured to use annotations can now be determined from the connection, so this can be automatic, without a translator override
> TEIID-4409 the option to determine if configured to use annotations 

- connectors/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/InfinispanHotRodExecutionFactory.java
- connectors/translator-infinispan-libmode/src/main/java/org/teiid/translator/infinispan/libmode/InfinispanLibModeExecutionFactory.java
TEIID-4510 fix the method getMaxFromGroups()to return 1, so that each table is independently queried and the results are joined in the teiid engine
> TEIID-4510 fix the method getMaxFromGroups()to return 1

- teiid-feature-pack/wildfly-integration-feature-pack/src/main/resources/modules/system/layers/dv/org/wololo/jts2geojson/main/module.xml
- teiid-feature-pack/wildfly-integration-feature-pack/src/main/resources/subsystem-templates/teiid-logging.xml
- teiid-feature-pack/wildfly-integration-feature-pack/src/main/resources/subsystem-templates/teiid.xml
- test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestDeployment.java
- test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestRestWebserviceGeneration.java
Fix the tests failed,:
* IntegrationTestDeployment.testTraslators - fixed
* IntegrationTestDeployment.testGeometry - fixed
* IntegrationTestDeployment.testGetRequests - add sleep half second after jdbc client close, in my test, not every time this test failed, I think the failed due to memory and cpu, after add sleep half second, it build success every time.
* IntegrationTestRestWebserviceGeneration.testSemanticVersion - current skipped, TEIID-4570 address this, I think we can move to Alpha2 to fix this.
> TEIID-4437: fix some arquillian tests failed issue

- connectors/connector-infinispan-dsl/src/main/java/org/teiid/resource/adapter/infinispan/dsl/DSLSearch.java
- connectors/connector-infinispan-dsl/src/main/java/org/teiid/resource/adapter/infinispan/dsl/InfinispanConnectionImpl.java
- connectors/connector-infinispan.6/src/main/java/org/teiid/resource/adapter/infinispan/DSLSearch.java
- connectors/translator-infinispan-dsl/src/main/java/org/teiid/translator/infinispan/dsl/metadata/ProtobufMetadataProcessor.java
- connectors/translator-object/src/main/java/org/teiid/translator/object/metadata/JavaBeanMetadataProcessor.java
- connectors/translator-object/src/test/resources/tradeMatMetadataFromVDB.ddl
TEIID-4588 changes the metadata processor to create unique tables and columns for the staging table, TEIID-4590 changed select ALL logic to so that a single cache can contain multiple root pojo's that can separate resource-adapters for access the data
> TEIID-4588 and TEIID-4590 

- connectors/infinispan/translator-object/src/main/java/org/teiid/translator/object/ObjectUpdateExecution.java
- connectors/infinispan/translator-object/src/test/java/org/teiid/translator/object/TestObjectUpdateExecution.java
TEIID-4603 Changing the logic so that when an insert of the root object is to be done, the get(key) method is called, instead of using the DSL searching. This will ensure an object is returned and an exception is thrown due to a duplicate object with this key already exist.
> TEIID-4603

- connectors/odata/translator-odata/src/main/java/org/teiid/translator/odata/ODataExecutionFactory.java
- connectors/odata/translator-odata/src/main/java/org/teiid/translator/odata/ODataPlugin.java
- connectors/odata/translator-odata/src/main/java/org/teiid/translator/odata/ODataSQLVisitor.java
- connectors/odata/translator-odata/src/main/resources/org/teiid/translator/odata/i18n.properties
- connectors/odata/translator-odata/src/test/java/org/teiid/translator/odata/TestODataSQLVistor.java
For instance, some servers choke on "startswith('a', 'b') eq true"
whereas "startswith('a', 'b')" is fine.
> #TEIID-4613 Add support for servers not handling comparisons for boolean functions

- connectors/infinispan/connector-infinispan-libmode/src/test/java/org/teiid/resource/adapter/infinispan/TestInfinispanUpdateExecution.java
- connectors/infinispan/translator-object/src/main/java/org/teiid/translator/object/ObjectUpdateExecution.java
- connectors/infinispan/translator-object/src/test/java/org/teiid/translator/object/TestObjectUpdateExecution.java
TEIID-4611 fixed the logic that was failing on deletes.  First, missed a return after the log message, which then threw the error message, but didn't really need the additional logic to recheck for the deleted object, so removed that extra check.
> TEIID-4611 fixed the logic that was failing on deletes.

- connectors/jdbc/translator-prestodb/src/main/java/org/teiid/translator/prestodb/PrestoDBExecutionFactory.java
As per prestodb document [1], "Support for correlated subqueries is limited. Not every standard form is supported." So set disable corelated subquery in translator
[1] https://prestodb.io/docs/current/sql/select.html
> TEIID-4687: disable corelated subquery in translator

- connectors/jdbc/translator-prestodb/src/main/java/org/teiid/translator/prestodb/PrestoDBExecutionFactory.java
* [TEIID-4682](https://issues.jboss.org/browse/TEIID-4682) - prestodb driver not support commit or set autocommit, if any of transactions related functions be invoked, a exception will through.
> TEIID-4682: fix prestodb could not commit transaction

- connectors/cassandra/connector-cassandra/src/main/java/org/teiid/resource/adapter/cassandra/CassandraConnectionImpl.java
- connectors/cassandra/feature-pack-cassandra/src/main/resources/modules/system/layers/dv/com/datastax/cassandra/driver/core/main/module.xml
- connectors/cassandra/translator-cassandra/src/main/java/org/teiid/translator/cassandra/CassandraMetadataProcessor.java
- connectors/cassandra/translator-cassandra/src/main/java/org/teiid/translator/cassandra/CassandraQueryExecution.java
- pom.xml
Upgrade datastax cassandra driver from version 2.1.3 to 3.1.3, including some api change:
* get version api has a tiny change
* datatype name enum remove the java class type
> TEIID-4476: Upgrade Cassandra Client library

- build/kits/jboss-as7/overlay/docs/teiid/teiid-releasenotes.html
- engine/src/main/java/org/teiid/query/processor/relational/DependentCriteriaProcessor.java
- engine/src/test/java/org/teiid/query/processor/TestDependentJoins.java
TEIID-4976: criteria duplicated when criteria includes the same columns as dependent join criteria (removing duplicate criteria)
> Backport of TEIID-4976: criteria duplicated when criteria includes the same colums

- engine/src/main/java/org/teiid/query/optimizer/relational/rules/RulePushAggregates.java
- engine/src/test/java/org/teiid/query/processor/TestAggregateProcessing.java
BZ1451870 + TEIID-4875 backport: addressing another issue with multiple decompositions
> BZ1451870 + TEIID-4875 backport

- connectors/misc/translator-jpa/src/main/java/org/teiid/translator/jpa/JPAMetadataProcessor.java
- connectors/misc/translator-jpa/src/main/java/org/teiid/translator/jpa/JPQLSelectVisitor.java
- connectors/misc/translator-jpa/src/test/java/org/teiid/translator/jpa/TestJSelectJPQLVisitor.java
- connectors/misc/translator-jpa/src/test/resources/sakila.ddl
This prevents column collisions and query failures involving Embedded
mappings by keeping track of the ManagedType traversal. Fragments of the
path are joined by '_' to form the column name. They are joined by '.'
and stored in nameInSource to be used in JPQL queries.
> TEIID-5404: translator-jpa: Improve Embedded mappings handling.

- connectors/infinispan/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/InfinispanDirectQueryExecution.java
[TEIID-5270] removing truncating the staging table after swapping names so that current queries can complete with the state it started with
> [TEIID-5270] removing truncating the staging table

- data-quality/pom.xml
- teiid-feature-pack/wildfly-integration-feature-pack/src/main/resources/modules/system/layers/dv/org/arrahtec/main/module.xml
opencsv is no longer in use, as far as I can discern. The project builds fine without the dependency.
> Removed superfluous dependency on opencsv

- jboss-integration/src/main/java/org/teiid/jboss/TeiidOperationHandler.java
Not using the upstream way of overriding describeParameters(), as that caused errors with missing descriptions.
> TEIID-5413 Fix failing cli calls

- engine/src/main/java/org/teiid/query/util/TeiidTracingUtil.java
- teiid-feature-pack/client-feature-pack/src/main/resources/modules/system/layers/dv/io/opentracing/teiid/module.xml
- teiid-feature-pack/client-feature-pack/src/main/resources/modules/system/layers/dv/org/jboss/teiid/client/main/module.xml
- teiid-feature-pack/wildfly-integration-feature-pack/src/main/resources/modules/system/layers/dv/org/jboss/teiid/main/module.xml
need to move our io.opentracing module to a slot to not conflict with
the throntail module of the same name
moved opentracing-concurrent to a direct resource as it seemed to fail
as a separate module?
minor cleanup to the tracing util
> TEIIDTOOLS-466 allowing for opentracing to be used in thorntail

- connectors/pom.xml
This needs to be backported to 13.0.x
> Include infinispan connector in all builds, including core-release

- api/src/main/java/org/teiid/adminapi/impl/DataPolicyMetadata.java
- api/src/main/java/org/teiid/connector/DataPlugin.java
- api/src/main/java/org/teiid/language/SQLConstants.java
- api/src/main/java/org/teiid/metadata/Database.java
- api/src/main/java/org/teiid/metadata/Grant.java
- api/src/main/java/org/teiid/metadata/MetadataFactory.java
- api/src/main/java/org/teiid/metadata/MetadataStore.java
- api/src/main/java/org/teiid/metadata/Permission.java
- api/src/main/java/org/teiid/metadata/Policy.java
- api/src/main/java/org/teiid/metadata/Role.java
- api/src/main/resources/org/teiid/connector/i18n.properties
- engine/src/main/java/org/teiid/dqp/internal/process/DQPWorkContext.java
- engine/src/main/java/org/teiid/query/metadata/DDLStringVisitor.java
- engine/src/main/java/org/teiid/query/metadata/DatabaseStore.java
- engine/src/main/java/org/teiid/query/metadata/DatabaseUtil.java
- engine/src/main/java/org/teiid/query/metadata/TransformationMetadata.java
- engine/src/main/java/org/teiid/query/optimizer/relational/RowBasedSecurityHelper.java
- engine/src/main/java/org/teiid/query/optimizer/relational/rules/RuleApplySecurity.java
- engine/src/main/javacc/org/teiid/query/parser/SQLParser.jj
- engine/src/test/java/org/teiid/query/metadata/TestDDLStringVisitor.java
- engine/src/test/java/org/teiid/query/parser/TestDDLParser.java
- engine/src/test/java/org/teiid/query/processor/TestRowPolicies.java
- runtime/src/main/java/org/teiid/deployers/CompositeVDB.java
- runtime/src/main/java/org/teiid/runtime/AbstractVDBDeployer.java
- runtime/src/main/java/org/teiid/runtime/EmbeddedServer.java
- runtime/src/test/resources/portfolio-converted-vdb.ddl
- runtime/src/test/resources/portfolio-vdb.ddl
- wildfly/test-integration/common/src/test/java/org/teiid/jdbc/TestRowBasedSecurity.java
this is roughly based on pg, but the name is scoped to both the resource
and the role - that's why drop takes both arguments.
it has been simplified to only specify a using condition, which defaults
to a constraint/check.  if you want to create separate read/write
policies, you need add two policies instead of one.
this does not yet attempt to rewrite the old permission condition logic
as policies
> TEIID-5798 adding the concept of a row policy

- connectors/jdbc/translator-jdbc/src/main/java/org/teiid/translator/jdbc/postgresql/PostgreSQLMetadataProcessor.java
Based on exceptions in the log file I found an error in the PostgreSQLMetadataProcessor. The table names for geometry metadata tables are mixed-up.
> Fixed wrong table names for geometry metadata tables
