admin/src/main/java/org/teiid/adminapi/AdminFactory.java

Change CancelRequest implementation from `terminate-session` to `cancel-request`

TEIID-3415: Adminapi CancelRequest implementation terminal the session

---

adminshell/src/main/java/org/teiid/adminshell/AdminHelpCommand.java
adminshell/src/main/java/org/teiid/adminshell/SqlHelpCommand.java
pom.xml

TEIID-3204 upgrading groovy and jline versions and backporting changes to support groovy upgrade

TEIID-3204 upgrading groovy and jline versions

---

build/kits/adminshell/README_EXAMPLES.txt
build/kits/adminshell/examples/DeployAndVerifyVDB.groovy
build/kits/adminshell/examples/DeployJar.groovy
build/kits/adminshell/examples/PrintVDBInfo.groovy
build/kits/adminshell/examples/RestartServer.groovy
build/kits/adminshell/examples/SetConnectionTypeForVDB.groovy

This also needs to be pushed to the 62-8.7.x branch.

TEIID-3458 added and updated example groovy scripts

---

build/kits/jboss-as7/overlay/standalone/configuration/standalone-teiid.xml
connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/hana/ConcatFunctionModifier.java
connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/hana/HanaExecutionFactory.java
connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/hana/HanaMetadataProcessor.java
connectors/translator-jdbc/src/main/resources/META-INF/services/org.teiid.translator.ExecutionFactory
connectors/translator-jdbc/src/test/java/org/teiid/translator/jdbc/hana/TestHanaConvertModifier.java

Initial commit of HANA translator.

teiid-3151

---

connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/hana/HanaExecutionFactory.java
connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/hana/Log10FunctionModifier.java
connectors/translator-jdbc/src/test/java/org/teiid/translator/jdbc/hana/TestHanaTranslator.java
connectors/translator-jdbc/src/test/java/org/teiid/translator/jdbc/hana/TestLog10FunctionModifier.java

Added all data mappings and function modifiers. Also corrected unit tests and validated generated statements against a HANA instance.

teiid-3151: 

---

build/kits/jboss-as7/overlay/bin/scripts/teiid-domain-auditcommand-logging.cli
build/kits/jboss-as7/overlay/bin/scripts/teiid-standalone-auditcommand-logging.cli

TEIID-3577 adding scripts to install audit and command logging with async-handlers

TEIID-3577 adding scripts to install audit and command logging

---

build/kits/jboss-as7/overlay/docs/teiid/datasources/phoenix/create-phoenix-ds.cli
build/kits/jboss-as7/overlay/docs/teiid/datasources/phoenix/phoenix-ds.xml
build/kits/jboss-as7/overlay/docs/teiid/datasources/phoenix/phoenix.xml
connectors/translator-hbase/src/main/java/org/teiid/translator/hbase/HBaseSQLConversionVisitor.java
connectors/translator-hbase/src/test/java/org/teiid/translator/hbase/TestSQLConversionVisitor.java
connectors/translator-hbase/src/test/resources/customer.ddl

* TEIID-3621: remove AssertionError, update should not depend upon a primary key
* TEIID-3619: update docs, set phoenix.connection.autoCommit property to true is necessary if execute INSERT/UPDATE/DELETE

TEIID-3621: remove AssertionError, update should not depend upon a pk

---

connectors/translator-hive/src/main/java/org/teiid/translator/hive/ImpalaExecutionFactory.java

Added missing type mapping for Teiid bigdecimal to Impala Decimal data type

Added type mapping for BigDecimal to Decimal

---

build/kits/jboss-as7/modules/org/jboss/teiid/main/module.xml
jboss-integration/src/main/java/org/teiid/jboss/rest/ApiOriginFilter.java
jboss-integration/src/main/java/org/teiid/jboss/rest/BootstrapServlet.java
jboss-integration/src/main/java/org/teiid/jboss/rest/TeiidRSExceptionHandler.java
jboss-integration/src/main/resources/rest-war/web.xml

The ExceptionMapper will return error as a xml:
~~~
<error>
<code>ERROR</code>
<message>message</message>
<details>stacktrace</details>
</error>
~~~

TEIID-3690: add a ExceptionMapper for generated rest war

---

build/kits/jboss-as7/overlay/bin/scripts/teiid-domain-auditcommand-logging.cli
build/kits/jboss-as7/overlay/bin/scripts/teiid-domain-mode-install.cli
build/kits/jboss-as7/overlay/bin/scripts/teiid-standalone-auditcommand-logging.cli
build/kits/jboss-as7/overlay/bin/scripts/teiid-standalone-mode-install.cli

changed standalone and domain to install AUDIT_LOG so that any followup cli script assumes its there and will therefore have a remove command.

changed standalone and domain to install AUDIT_LOG 

---

connectors/connector-ws/kits/jboss-as7/modules/org/springframework/spring/main/module.xml

TEIIDDES-2791 when adding back the spring jars, missed adding the nee…ded dependency to logging

TEIIDDES-2791 add in dependency

---

engine/src/main/resources/org/teiid/metadata/SYSADMIN.sql
test-integration/common/src/test/java/org/teiid/systemmodel/TestMatViews.java
test-integration/common/src/test/resources/TestSystemVirtualModel/testStoredProcedures.expected

update loadmatview as a universal procedure that can update both Internal and External Mat View

TEIID-4142: update loadmatview as a universal procedure to update Mat View

---

connectors/connector-infinispan-dsl/kits/jboss-as7/modules/org/jboss/teiid/resource-adapter/infinispan/dsl/main/module.xml
connectors/connector-infinispan-dsl/src/main/rar/META-INF/MANIFEST.MF
connectors/connector-infinispan-dsl/src/test/java/org/teiid/resource/adapter/infinispan/dsl/TesttInfinispanConnectionFactory.java

TEIID-4150 fixed module.xml and dependencies in manifest, also, fixed a unit test

TEIID-4150 fixed module.xml and dependencies in manifest

---

engine/src/main/resources/org/teiid/query/i18n.properties

Silly commit, but clients can see these things, so we might as well fix them.

TEIID-4215 Fixed a bunch of typos in error messages

---

test-integration/perf/src/test/java/org/teiid/sizing/Caculation.java
test-integration/perf/src/test/java/org/teiid/sizing/TestSizingApplication.java

* add test code for verify sizing app version 1's formula

TEIID-3355: Sizing Application enhancement

---

olingo/src/main/java/org/teiid/olingo/ODataPlugin.java
olingo/src/main/java/org/teiid/olingo/web/ODataFilter.java
olingo/src/main/java/org/teiid/olingo/web/StaticContentServlet.java
olingo/src/main/resources/org/teiid/olingo/i18n.properties
olingo/src/main/webapp/WEB-INF/web.xml
test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestOData4.java

allow valid metadata documents, also fixed an issue in web.xml with correct
mapping for static servlet

TEIID-4090: refining the Static Servlet behavior to only

---

olingo/src/main/java/org/teiid/olingo/ODataPlugin.java
olingo/src/main/java/org/teiid/olingo/web/ODataFilter.java
olingo/src/main/java/org/teiid/olingo/web/StaticContentServlet.java
olingo/src/main/resources/org/teiid/olingo/i18n.properties
olingo/src/main/webapp/WEB-INF/web.xml
test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestOData4.java

allow valid metadata documents, also fixed an issue in web.xml with correct
mapping for static servlet

TEIID-4090: refining the Static Servlet behavior to only (#723)

---

connectors/translator-file/src/main/java/org/teiid/translator/file/FileExecutionFactory.java
connectors/translator-file/src/main/resources/org/teiid/translator/file/i18n.properties

Add deleteFile call to file translator

---

connectors/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/InfinispanManagedConnectionFactory.java

TEIID-4329 changed to specify the package name when the class is registered

TEIID-4329 changed to specify the package name when the class is registered

---

connectors/connector-infinispan-hotrod/kits/wildfly/modules/org/jboss/teiid/resource-adapter/infinispan/hotrod/main/module.xml
connectors/connector-infinispan-libmode/kits/wildfly/modules/org/jboss/teiid/resource-adapter/infinispan/libmode/module.xml
connectors/translator-infinispan-hotrod/kits/wildfly/modules/org/jboss/teiid/translator/infinispan/hotrod/main/module.xml
connectors/translator-infinispan-libmode/kits/wildfly/modules/org/jboss/teiid/translator/infinispan/libmode/main/module.xml

TEIID-4358 adding dependencies to support 2 prior versions:  JDG 6.6 and 6.5

TEIID-4358 adding dependencies to support 2 prior versions

---

connectors/connector-infinispan-hotrod/pom.xml
connectors/connector-infinispan-hotrod/src/test/resources/infinispan_remote_config.xml
connectors/connector-infinispan-libmode/pom.xml
connectors/translator-infinispan-hotrod/pom.xml
connectors/translator-infinispan-hotrod/src/test/java/org/jboss/as/quickstarts/datagrid/hotrod/query/domain/PersonCacheSource.java
connectors/translator-infinispan-hotrod/src/test/java/org/jboss/teiid/jdg_remote/pojo/AllTypesCacheSource.java
connectors/translator-infinispan-libmode/pom.xml
pom.xml

Updated infinispan to version 8.0.3, which is the version that's in the jdg-7.0 slot in the eap module kits

Updated infinispan to version 8.0.3

---

olingo/src/main/java/org/teiid/olingo/ODataPlugin.java
olingo/src/main/java/org/teiid/olingo/web/CorsFilter.java
olingo/src/main/java/org/teiid/olingo/web/ODataFilter.java
olingo/src/main/java/org/teiid/olingo/web/StaticContentServlet.java
olingo/src/main/resources/org/teiid/olingo/i18n.properties
olingo/src/main/webapp/WEB-INF/web.xml
test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestOData4.java

* Revert "TEIID-4297 (#763)"
This reverts commit c23f13c6bdb9cf7a186fc65394b699a79a731824.
* TEIID-4366: Adding CORS support to the OData web service

Teiid 4366 (#786)

---

connectors/connector-infinispan-hotrod/kits/wildfly/modules/org/jboss/teiid/resource-adapter/infinispan/hotrod/main/META-INF/ra.xml
connectors/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/InfinispanManagedConnectionFactory.java
connectors/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/schema/AnnotationSchema.java
connectors/connector-infinispan-hotrod/src/test/java/org/teiid/resource/adapter/infinispan/hotrod/TestInfinispanConfigFileRemoteCache.java

TEIID-4492 added ChildClasses option for configuring all pojos using protubuf annotations

TEIID-4492 added ChildClasses option

---

connectors/infinispan/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/DSLSearch.java
connectors/infinispan/connector-infinispan-hotrod/src/main/java/org/teiid/resource/adapter/infinispan/hotrod/InfinispanConnectionImpl.java
connectors/infinispan/connector-infinispan-libmode/src/main/java/org/teiid/resource/adapter/infinispan/DSLSearch.java
connectors/infinispan/connector-infinispan-libmode/src/main/java/org/teiid/resource/adapter/infinispan/InfinispanCacheRAConnection.java
connectors/infinispan/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/metadata/ProtobufMetadataProcessor.java
connectors/infinispan/translator-object/src/main/java/org/teiid/translator/object/metadata/JavaBeanMetadataProcessor.java
connectors/infinispan/translator-object/src/test/resources/tradeMatMetadataFromVDB.ddl

TEIID-4588 and TEIID-4597 fixed the issue when materialization is determined for exposing metadata and fixed the issue related to duplicate columns due to reusing columns from the primary table, need to create unique columns for the staging table

TEIID-4588 and TEIID-4597

---

test-integration/perf/src/test/java/org/teiid/sizing/Caculation.java
test-integration/perf/src/test/java/org/teiid/sizing/TestSizingApplication.java

- This commits including the test for new change of the web sizing application described in TEIID-4489.
- The commits also for the test code compatible with latest web app

TEIID-4489: add a isRunOnCloud to allow recommend small size

---

engine/src/main/java/org/teiid/dqp/internal/datamgr/ConnectorWorkItem.java
engine/src/main/java/org/teiid/query/processor/proc/ProcedurePlan.java

TEIID-4782: handling the runtime exceptions thrown by translators and resource adapters in procedure block, also wrap them in TranslatorException automatically

Teiid 4782 (#907)

---

connectors/cassandra/translator-cassandra/src/main/java/org/teiid/translator/cassandra/CassandraMetadataProcessor.java
connectors/cassandra/translator-cassandra/src/main/java/org/teiid/translator/cassandra/CassandraSQLVisitor.java
connectors/cassandra/translator-cassandra/src/test/java/org/teiid/translator/cassandra/TestTeiidLanguageToCQL.java

Implemented TEIID-4717

---

connectors/connector-infinispan-dsl/src/main/java/org/teiid/resource/adapter/infinispan/dsl/InfinispanManagedConnectionFactory.java

TEIID-4793 fixed class loading so that the pojo doesn't require dependency to RA

TEIID-4793 fixed class loading

---

jboss-security/src/main/java/org/teiid/jboss/oauth/OAuth20CredentialImpl.java
jboss-security/src/main/java/org/teiid/jboss/oauth/OAuth20LoginModule.java

TEIID-4826 Adds option to provide access_token directly in login-module.

TEIID-4826 OAuth2 added option to set access-token directly.

---

connectors/webservice/connector-ws/src/main/java/org/teiid/oauth/OAuthUtil.java

Base on current utils, the generate facebook oauth2 login configuration looks
~~~
Select type of OAuth authentication
1) OAuth 1.0A
2) OAuth 2.0
3) OAuth 2.0 - Facebook
3
=== OAuth 2.0 - Facebook Workflow ===
Enter the App ID = 862553450566543
Enter the App Secret = 577440b169b4123sdsdfra497e83feae26
Enter the User Authorization URL(default: https://www.facebook.com/v2.9/dialog/oauth) = 
Enter scope (default: public_profile,user_friends,email,pages_manage_cta) = 
Enter callback URL (the redirect url match the setting in your Facebook App) = http://teiid.jboss.org/
Cut & Paste the URL in a web browser, and Authticate
Authorize URL  = https://www.facebook.com/v2.9/dialog/oauth?client_id=862553450566543&scope=public_profile,user_friends,email,pages_manage_cta&response_type=code&redirect_uri=h …

TEIID-4552: add a option for facebook in oauth util

---

build/kits/jboss-as7/overlay/docs/teiid/teiid-releasenotes.html
engine/src/main/java/org/teiid/query/optimizer/relational/RelationalPlanner.java
engine/src/main/java/org/teiid/query/optimizer/relational/rules/RuleConstants.java
engine/src/main/java/org/teiid/query/optimizer/relational/rules/RulePushLargeIn.java
engine/src/test/java/org/teiid/query/processor/TestDependentJoins.java

BZ1417982 (6.3.6) + TEIID-4901: Add parallel source query handling for when IN criteria values exceed MaxInCriteriaSize for translator (pushing large in as dependent set)

BZ1417982 (6.3.6) + TEIID-4901: Add parallel source query handling

---

build/kits/jboss-as7/overlay/docs/teiid/teiid-releasenotes.html
engine/src/main/java/org/teiid/query/optimizer/relational/rules/RulePushAggregates.java
engine/src/main/java/org/teiid/query/processor/relational/RelationalNode.java
engine/src/test/java/org/teiid/query/processor/TestAggregateProcessing.java

TEIID-4875: Planning issue with multiple aggregate decompositions through a join tree (fixing aggregate planning issue)

TEIID-4875: Planning issue with multiple aggregate decompositions thru join tree

---

build/kits/jboss-as7/overlay/docs/teiid/teiid-releasenotes.html
engine/src/main/java/org/teiid/query/processor/relational/DependentAccessNode.java
engine/src/test/java/org/teiid/query/processor/TestDependentJoins.java

TEIID-4722: TEIID30019: java.lang.AssertionError: Assertion failed assertion due to guard against a corner condition. (preventing an assertion error)

TEIID-4722: TEIID30019: java.lang.AssertionError: Assertion failed

---

connectors/couchbase/translator-couchbase/src/main/java/org/teiid/translator/couchbase/CouchbaseMetadataProcessor.java
connectors/couchbase/translator-couchbase/src/test/java/org/teiid/translator/couchbase/TestCouchbaseMetadataProcessor.java
connectors/couchbase/translator-couchbase/src/test/resources/moreTypedNameInOneKeyspace.expected

TEIID-4933: add sampleKeyspaces property, support multiple typed name per keyspace

---

common-core/src/main/java/org/teiid/core/types/BlobImpl.java
common-core/src/test/java/org/teiid/core/types/TestBlobValue.java

Revert "let's reset the input stream before converting the stream to a byte a…"

---

build/kits/jboss-as7/overlay/bin/scripts/teiid-domain-mode-install.cli
build/kits/jboss-as7/overlay/bin/scripts/teiid-standalone-ha-mode-install.cli
build/kits/jboss-as7/overlay/bin/scripts/teiid-standalone-mode-install.cli

TEIID-5032 - removing configuration of infinispan translator and resource-adapter will need to run CLI script to integrate JDG

TEIID-5032 - removing configuration of infinispan translator and resource-adapter

---

connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/pi/PIExecutionFactory.java
connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/pi/PIMetadataProcessor.java
connectors/translator-jdbc/src/main/java/org/teiid/translator/jdbc/pi/PISQLConversionVisitor.java
connectors/translator-jdbc/src/test/java/org/teiid/translator/jdbc/pi/TestPIExecutionFactory.java

OsiSoftPi changes for jiras TEIID-5116, TEIID-5117, TEIID-5118, TEIID-5120, TEIID-5122

OsiSoftPi changes

---

connectors/jdbc/translator-jdbc/src/main/java/org/teiid/translator/jdbc/h2/H2ExecutionFactory.java
connectors/jdbc/translator-jdbc/src/main/java/org/teiid/translator/jdbc/postgresql/PostgreSQLExecutionFactory.java

TEIID-5190 adding group by function support for H2 and PostgreSQL for 9.3.x branch.

TEIID-5190 adding group by function support for H2 and PostgreSQL for 9.3.x branch

---

connectors/connector-mongodb/src/main/java/org/teiid/resource/adapter/mongodb/MongoDBManagedConnectionFactory.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MergeDetails.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDBDirectQueryExecution.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDBExecutionFactory.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDBMetadataProcessor.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDBSelectVisitor.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDBUpdateExecution.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDBUpdateVisitor.java
connectors/translator-mongodb/src/main/java/org/teiid/translator/mongodb/MongoDocument.java
connectors/translator-mongodb/src/test/java/org/teiid/translator/mongodb/TestMongoDBMetadataProcessor.java
pom.xml

This pr combines TEIID-4781 with an upgrade to the latest mongo java client with the TEIID-5291 commit.

Teiid 5291

---

README.md

One should be able to build and run teiid just looking at README.
Would you support adding a short paragraph on adding a simple vdb and issuing a query?

Added quick start instructions

---

.gitignore
connectors/jdbc/translator-jdbc/src/main/java/org/teiid/translator/jdbc/exasol/ExasolExecutionFactory.java
connectors/jdbc/translator-jdbc/src/main/resources/META-INF/services/org.teiid.translator.ExecutionFactory
connectors/jdbc/translator-jdbc/src/test/java/org/teiid/translator/jdbc/exasol/TestExasolTranslator.java
teiid-feature-pack/wildfly-integration-feature-pack/src/main/resources/subsystem-templates/teiid.xml
test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestDeployment.java

https://issues.jboss.org/browse/TEIID-4520

TEIID-4520 Support for Exasol translator

---

connectors/misc/translator-jpa/src/main/java/org/teiid/translator/jpa/JPAMetadataProcessor.java

This simply exposes them as string columns.

TEIID-5349: JPAMetadataProcessor: Added support for Enum properties.

---

connectors/jdbc/translator-jdbc/src/main/java/org/teiid/translator/jdbc/exasol/ExasolExecutionFactory.java

Need to push down correlated subqueries and byte conversion

TEIID-4520 Fixed byte conversion and correlated subqueries

---

test-integration/common/src/test/java/org/teiid/arquillian/IntegrationTestDeployment.java

fix typo: traslator -> translator

fix typos in IntegrationTestDeployment.java

---

cache-infinispan/pom.xml
cache-infinispan/src/main/java/org/teiid/cache/infinispan/EmbeddedInfinispanCacheFactoryBuilder.java
cache-infinispan/src/main/java/org/teiid/cache/infinispan/InfinispanCacheFactory.java
olingo/src/test/java/org/teiid/olingo/TestODataIntegration.java
runtime/pom.xml
runtime/src/main/java/org/teiid/runtime/EmbeddedConfiguration.java
runtime/src/main/java/org/teiid/runtime/EmbeddedServer.java
runtime/src/main/java/org/teiid/runtime/RuntimePlugin.java
runtime/src/main/resources/org/teiid/runtime/i18n.properties
runtime/src/test/java/org/teiid/runtime/TestEmbeddedServer.java
wildfly/teiid-feature-pack/wildfly-integration-feature-pack/teiid-releasenotes.html
wildfly/test-integration/common/src/test/java/org/teiid/jdbc/FakeServer.java
wildfly/test-integration/common/src/test/java/org/teiid/runtime/ReplicatedServer.java

Here's the follow on changes described in the other pull request.

TEIID-5596 further refinements to the infinispan separation

---

pom.xml

* [TEIID-5660] Change to use javadoc 3.0.0.M1 from basepom

[TEIID-5660] Change to use javadoc 3.0.0.M1 from basepom

---

srcclr.yml

It needs the settings.xml, ortherwise it can't find the oreva jar's.

[TEIIDTOOLS-717] Update srcclr command

---

admin/src/main/java/org/teiid/adminapi/impl/DataPolicyMetadata.java
admin/src/test/java/org/teiid/adminapi/impl/TestDataPolicyMetaData.java
api/src/main/java/org/teiid/PolicyDecider.java
engine/src/main/java/org/teiid/dqp/internal/process/AuthorizationValidationVisitor.java
engine/src/main/java/org/teiid/dqp/internal/process/DataRolePolicyDecider.java
engine/src/main/java/org/teiid/dqp/internal/process/DefaultAuthorizationValidator.java
engine/src/main/java/org/teiid/query/optimizer/relational/ColumnMaskingHelper.java
engine/src/main/java/org/teiid/query/optimizer/relational/RowBasedSecurityHelper.java
engine/src/main/java/org/teiid/query/optimizer/relational/rules/RuleApplySecurity.java
engine/src/test/java/org/teiid/dqp/internal/process/TestAuthorizationValidationVisitor.java
engine/src/test/java/org/teiid/query/metadata/TestDDLStringVisitor.java

- adds the type to permission checks to prevent resource ambiguity
- passes AbstractMetadataRecord(s) to the PolicyDecider

TEIID-5842 TEIID-5841 refining the policy security logic

---

client/src/main/java/org/teiid/jdbc/BaseDataSource.java
client/src/main/java/org/teiid/jdbc/ExecutionProperties.java
client/src/main/java/org/teiid/jdbc/JDBCURL.java
client/src/main/java/org/teiid/jdbc/StatementImpl.java
client/src/main/resources/org/teiid/jdbc/i18n.properties
client/src/test/java/org/teiid/jdbc/TestTeiidDriver.java
connectors/document-api/src/main/java/org/teiid/translator/document/Document.java
connectors/infinispan/infinispan-api/src/main/java/org/teiid/infinispan/api/DocumentFilter.java
connectors/infinispan/infinispan-api/src/main/java/org/teiid/infinispan/api/InfinispanDocument.java
connectors/infinispan/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/ComplexDocumentFilter.java
connectors/infinispan/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/InfinispanExecutionFactory.java
connectors/infinispan/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/InfinispanResponse.java
wildfly/connectors/infinispan/connector-infinispan-hotrod/src/test/java/org/teiid/translator/infinispan/hotrod/TestHotrodExecution.java

- the logic only supports a single explicit join
- the update count calculation always counts the parent
- the filter logic is acting against implicit/unrelated children

TEIID-5888 addressing misc ispn issues:

---

engine/src/main/java/org/teiid/dqp/internal/process/MetaDataProcessor.java
engine/src/main/java/org/teiid/dqp/internal/process/RequestWorkItem.java
engine/src/main/java/org/teiid/query/sql/symbol/AggregateSymbol.java
engine/src/main/java/org/teiid/query/sql/symbol/Function.java
engine/src/main/java/org/teiid/query/sql/symbol/NamedExpression.java
engine/src/main/java/org/teiid/query/sql/symbol/WindowFunction.java
runtime/src/main/java/org/teiid/odbc/ODBCServerRemoteImpl.java
wildfly/test-integration/common/src/test/java/org/teiid/transport/TestODBCSocketTransport.java

for an unaliased column we'll use the function, aggregate, or window
function name for the column in the result set metadata

TEIID-5909 adding pg column naming

---

connectors/mongodb/mongodb-api/src/main/java/org/teiid/mongodb/MongoDBConfiguration.java
engine/src/main/java/org/teiid/query/metadata/MetadataValidator.java
engine/src/main/java/org/teiid/query/sql/lang/Command.java
wildfly/connectors/mongodb/connector-mongodb/src/main/java/org/teiid/resource/adapter/mongodb/MongoDBManagedConnectionFactory.java

also extracting common logic to a configuration interface

TEIID-5611 adding support for scram-sha-256

---

connectors/salesforce/translator-salesforce/src/main/java/org/teiid/salesforce/BaseSalesforceConnection.java
connectors/salesforce/translator-salesforce/src/main/java/org/teiid/salesforce/SalesforceConfiguration.java
wildfly/connectors/salesforce/connector-salesforce/src/main/java/org/teiid/resource/adapter/salesforce/SalesForceManagedConnectionFactory.java
wildfly/connectors/salesforce/connector-salesforce/src/main/java/org/teiid/resource/adapter/salesforce/SalesforceConnectionImpl.java
wildfly/connectors/salesforce/connector-salesforce/src/test/java/org/teiid/resource/adapter/salesforce/TestSalesforceConnectionImpl.java
wildfly/resource-spi/src/main/java/org/teiid/resource/spi/BasicConnectionFactory.java
wildfly/resource-spi/src/main/java/org/teiid/resource/spi/BasicManagedConnection.java
wildfly/resource-spi/src/main/java/org/teiid/resource/spi/BasicManagedConnectionFactory.java
wildfly/resource-spi/src/main/java/org/teiid/resource/spi/ResourceConnection.java

also making a pure interface version of basicconnection

TEIIDSB-184 creating a common salesforce base

---

connectors/infinispan/infinispan-api/src/main/java/org/teiid/infinispan/api/InfinispanPlugin.java
connectors/infinispan/infinispan-api/src/main/java/org/teiid/infinispan/api/ProtobufMetadataProcessor.java
connectors/infinispan/infinispan-api/src/main/resources/org/teiid/infinispan/api/i18n.properties
connectors/infinispan/translator-infinispan-hotrod/src/main/java/org/teiid/translator/infinispan/hotrod/SchemaToProtobufProcessor.java
connectors/infinispan/translator-infinispan-hotrod/src/test/java/org/teiid/translator/infinispan/hotrod/TestProtobufMetadataProcessor.java

also using source table names consistently and removing on more assumption of the default cache name

TEIID-5944 adding protobuf identifier validation

---

pom.xml

Fix for beanutils CVE-2019-10086 (ENTESB-12539)

---

pom.xml

Ignored the tests (fail, likely due to a Locale issue)

Fix for CVE-2019-10086 (ENTESB-12539)

---

pom.xml

Correction for dom4j CVE-2020-10683

---

pom.xml

Fix for netty-codec CVE-2020-11612

---

pom.xml

Correction for jackson-mapper-asl CVEs

---

connectors/amazon/translator-simpledb/src/main/java/org/teiid/translator/simpledb/api/BaseSimpleDBConfiguration.java

Signed-off-by: Mudit Jain <ciphereck@gmail.com>

Adds extra method for getting secretKey in simpledb

---

connectors/salesforce/translator-salesforce/src/main/java/org/teiid/translator/salesforce/execution/visitors/SelectVisitor.java
connectors/salesforce/translator-salesforce/src/test/java/org/teiid/translator/salesforce/execution/visitors/TestVisitors.java

This is fix of https://issues.redhat.com/browse/TEIID-6069

Order by fix

---

connectors/salesforce/translator-salesforce/src/main/java/org/teiid/translator/salesforce/execution/QueryExecutionImpl.java
connectors/salesforce/translator-salesforce/src/test/java/org/teiid/translator/salesforce/execution/TestQueryExecutionImpl.java

Fixed  https://issues.redhat.com/browse/TEIID-6073

Teiid 6073

---

common-core/src/main/java/org/teiid/core/util/PropertiesUtils.java
engine/src/main/java/org/teiid/query/eval/TeiidScriptEngine.java
engine/src/main/java/org/teiid/query/function/FunctionDescriptor.java
engine/src/main/java/org/teiid/query/function/FunctionTree.java
runtime/src/main/java/org/teiid/deployers/TranslatorUtil.java

https://issues.redhat.com/browse/TEIID-6099
Built successfully with JDK11.

TEIID-6099 Replace getParameterTypes().length with getParameterCount()
